name: Flutter Build

on:
  push:
    branches: [ main ]
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scanairz # 👈 important, your Flutter app is here

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: scanairz/build/app/outputs/flutter-apk/*.apk
