name: scanairz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  mobile_scanner: ^4.0.1
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  firebase_core: ^2.32.0
  firebase_app_check: ^0.2.2
  firebase_crashlytics: ^3.5.0
  intl: ^0.19.0
  share_plus: ^7.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
